---
site_name: PIFINA Documentation
site_url: https://pifina.app
repo_url: https://github.com/thushjandan/pifina
theme:
  name: material
  palette:
    primary: indigo
  logo: assets/logo.png
  favicon: assets/favicon.ico