/* -*- P4_16 -*- */
/**
* THIS FILE HAS BEEN GENERATED BY pifina.
* PIFINA P4 headers
*
* Copyright 2023 Thushjandan Ponnudurai
*
* This software may be modified and distributed under the terms
* of the MIT license.  See the LICENSE file for details.
*/


// Size of lookup table in bits. 7 bits = 127 entries
#define PF_TABLE_SIZE_WIDTH 7
#define PF_TABLE_SIZE 1<<PF_TABLE_SIZE_WIDTH

typedef bit<PF_TABLE_SIZE_WIDTH> pf_stats_width_t;

header pf_control_t {
    bool pfIsMatch;
    pf_stats_width_t pfSessionId;
}

struct pf_ingress_metadata_t {
    pf_control_t pfControl;
    bit<48> pfJitter;
    bit<48> pfArrivalLatency;
}

struct pf_egress_metadata_t {
    pf_control_t pfControl;
    bit<32> pfPacketLength;
}
