---
name: Build Pifina binaries

on:
  push:
    #branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pifina-sdk
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install Protoc
      uses: arduino/setup-protoc@v2

    - name: Install protobuf-golang plugin
      run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28

    - name: Install protobuf-golang-grpc plugin
      run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

    - name: Copy BFRT proto file
      run: echo "$PF_BFRT_PROTO_SRC" > internal/dataplane/tofino/protos/bfrt.proto
      env:
        PF_BFRT_PROTO_SRC: ${{ vars.PF_BFRT_PROTO_SRC }}

    - name: test
      run: cat internal/dataplane/tofino/protos/bfrt.proto

    - name: Generate self-signed cert
      run: >-
        openssl req -x509 -newkey  ec -pkeyopt ec_paramgen_curve:prime256v1
        -keyout assets/key.pem -out assets/cert.pem -sha256 -days 3650 -nodes
        -subj "/C=CH/O=Pifina/CN=PifinaServer"

    - name: Build Pifina proto
      run: >- 
        protoc --go_opt=Mpifina.proto=pifina/
        --go_out=./pkg/model/protos/pifina/
        --proto_path=./pkg/model/protos/
        ./pkg/model/protos/pifina.proto
