// Copyright (c) 2023 Thushjandan Ponnudurai
// 
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT

import { PROBE_INGRESS_MATCH_CNT_BYTE, PROBE_EGRESS_START_CNT_BYTE, PROBE_EGRESS_END_CNT_BYTE, PROBE_INGRESS_MATCH_CNT_PKT, PROBE_EGRESS_START_CNT_PKTS, PROBE_INGRESS_START_HDR_BYTE, PROBE_INGRESS_END_HDR_BYTE, PROBE_INGRESS_JITTER, PROBE_TM_INGRESS_DROP_PKT, PROBE_TM_EGRESS_DROP_PKT, PROBE_TM_INRESS_USAGE_CELLS, PROBE_TM_ERESS_USAGE_CELLS, PROBE_TM_PIPE_IG_FULL_BUF, PROBE_TM_PIPE_EG_DROP_PKT, PROBE_TM_PIPE_TOTAL_BUF_DROP, PROBE_NEO_RX_BW, PROBE_NEO_TX_BW, PROBE_NEO_RX_PKT, PROBE_NEO_TX_PKT, PROBE_NEO_PCI_IN_BW, PROBE_NEO_PCI_OUT_BW, PROBE_NEO_RX_FULL_0, PROBE_NEO_RX_FULL_1, PROBE_NEO_WQE_MISS, PROBE_NEO_PCI_BP, PROBE_NEO_ICM_MISS, PROBE_NEO_TPT_MTT_L0_MISS, PROBE_NEO_TPT_MTT_L1_MISS, PROBE_NEO_TPT_MPT_L0_MISS, PROBE_NEO_TPT_MPT_L1_MISS, PROBE_ETHTOOL_RX_DISCARD, PROBE_ETHTOOL_TX_DISCARD, PROBE_ETHTOOL_RX_PAUSE, PROBE_ETHTOOL_TX_PAUSE, PROBE_ETHTOOL_RX_OOB } from "$lib/models/metricNames";

export const PIFINA_DEFAULT_PROBE_CHART_ORDER = [
    PROBE_INGRESS_MATCH_CNT_BYTE, 
    [PROBE_EGRESS_START_CNT_BYTE, PROBE_EGRESS_END_CNT_BYTE], 
    [PROBE_INGRESS_MATCH_CNT_PKT, PROBE_EGRESS_START_CNT_PKTS], 
    [PROBE_INGRESS_START_HDR_BYTE, PROBE_INGRESS_END_HDR_BYTE], 
    PROBE_INGRESS_JITTER
];

export const PIFINA_TM_CHART_ORDER = [
    [PROBE_TM_INGRESS_DROP_PKT, PROBE_TM_EGRESS_DROP_PKT],
    [PROBE_TM_INRESS_USAGE_CELLS, PROBE_TM_ERESS_USAGE_CELLS],
    [PROBE_TM_PIPE_IG_FULL_BUF, PROBE_TM_PIPE_EG_DROP_PKT],
    PROBE_TM_PIPE_TOTAL_BUF_DROP
];

export const PIFINA_NEO_CHART_ORDER = [
    [PROBE_NEO_RX_BW, PROBE_NEO_TX_BW],
    [PROBE_NEO_RX_PKT, PROBE_NEO_TX_PKT],
    [PROBE_NEO_PCI_IN_BW, PROBE_NEO_PCI_OUT_BW],
    [PROBE_NEO_RX_FULL_0, PROBE_NEO_RX_FULL_1],
    [PROBE_NEO_WQE_MISS, PROBE_NEO_PCI_BP],
    PROBE_NEO_ICM_MISS,
    [PROBE_NEO_TPT_MTT_L0_MISS, PROBE_NEO_TPT_MTT_L1_MISS],
    [PROBE_NEO_TPT_MPT_L0_MISS, PROBE_NEO_TPT_MPT_L1_MISS]
]

export const PIFINA_ETHTOOL_CHART_ORDER = [
    [PROBE_ETHTOOL_RX_DISCARD, PROBE_ETHTOOL_TX_DISCARD],
    [PROBE_ETHTOOL_RX_PAUSE, PROBE_ETHTOOL_TX_PAUSE],
    PROBE_ETHTOOL_RX_OOB
]